/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-08 01:59:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.request;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class req_005fvideo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>req_video.jsp</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<!-- \r\n");
      out.write("		테이블 페이지에서 a태그의 url 주소 뒤에 있는 title변수로 각각의 식별값을 담아서 이동\r\n");
      out.write("		ok 페이지에서는 넘어오는 값에 따라서 if ~ else if ~ else 형태로 다른 화면이 보이게\r\n");
      out.write("		처리.\r\n");
      out.write("		 -->\r\n");
      out.write("		 \r\n");
      out.write("		 <div align=\"center\">	<!-- 블럭을 만들어 사용하는 태그 --> \r\n");
      out.write("		 	<table border=\"1\">\r\n");
      out.write("		 		<tr>\r\n");
      out.write("		 			<th>이미지</th>\r\n");
      out.write("		 			<th>장르</th>\r\n");
      out.write("		 			<th>이름</th>\r\n");
      out.write("		 			<th>등록일</th>\r\n");
      out.write("		 			\r\n");
      out.write("		 		</tr>\r\n");
      out.write("		 		<tr>\r\n");
      out.write("		 			<td>\r\n");
      out.write("		 				<a href=\"req_video_ok.jsp?num=1\">\r\n");
      out.write("		 					<img alt=\"첫 번째 영상\" src=\"../images/다운로드.jpg\" width=\"100\" height=\"100\">\r\n");
      out.write("		 				</a>\r\n");
      out.write("		 			</td>\r\n");
      out.write("		 			<td>프로그램</td>\r\n");
      out.write("		 			<td>파이썬 입문 수업</td>\r\n");
      out.write("		 			<td>24.04.08</td>\r\n");
      out.write("		 			\r\n");
      out.write("		 		</tr>\r\n");
      out.write("		 		<tr>\r\n");
      out.write("		 			<td>\r\n");
      out.write("		 				<a href=\"req_video_ok.jsp?num=2\">\r\n");
      out.write("		 					<img alt=\"두 번쨰 영상\" src=\"../images/다운로드.jpg\" width=\"100\" height=\"100\">\r\n");
      out.write("		 				</a>\r\n");
      out.write("		 			</td>\r\n");
      out.write("		 			<td>프로그램</td>\r\n");
      out.write("		 			<td>java 입문 수업(나도코딩)</td>\r\n");
      out.write("		 			<td>24.04.08</td>\r\n");
      out.write("		 			\r\n");
      out.write("		 		</tr>\r\n");
      out.write("		 	</table>\r\n");
      out.write("		 </div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
